// Generated by get_supported_quotes.ts from https://blockchain-swap.pump.fun/supported/coin-create-mints; do not edit.
import { PublicKey } from '@solana/web3.js';
const TOKEN_PROGRAM_ID = new PublicKey('TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA');
const TOKEN_2022_PROGRAM_ID = new PublicKey('TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb');
enum Quote {
    SOL = 'SOL',
    USDC = 'USDC',
    BTC = 'BTC',
    ETH = 'ETH',
    MU = 'MU',
    SPY = 'SPY',
    CRCL = 'CRCL',
    SKHY = 'SKHY',
    TSLA = 'TSLA',
    QQQ = 'QQQ',
    NVDA = 'NVDA',
    SPCX = 'SPCX',
    MSTR = 'MSTR',
    COIN = 'COIN',
    GLD = 'GLD',
    HOOD = 'HOOD',
    VIDA = 'VIDA',
    AAPL = 'AAPL',
    MCD = 'MCD',
    NKE = 'NKE',
    DRAM = 'DRAM',
    PLTR = 'PLTR',
    MSFT = 'MSFT',
    BOT = 'BOT',
    GOOGL = 'GOOGL',
    TTWO = 'TTWO',
    GPRO = 'GPRO',
    META = 'META',
    AMZN = 'AMZN',
    KO = 'KO',
    GME = 'GME',
    'BRK.B' = 'BRK.B',
    SNDK = 'SNDK',
    AMC = 'AMC',
    MRNA = 'MRNA',
    AVGO = 'AVGO',
    LLY = 'LLY',
    INTC = 'INTC',
    HYPE = 'HYPE',
    ZEC = 'ZEC',
    NEAR = 'NEAR',
    XRP = 'XRP',
    XMR = 'XMR',
    NBIS = 'NBIS',
    MRVL = 'MRVL',
    ORCL = 'ORCL',
    XOM = 'XOM',
    UNH = 'UNH',
    NFLX = 'NFLX',
    NVO = 'NVO',
    AMD = 'AMD',
    V = 'V',
    JPM = 'JPM',
    WMT = 'WMT',
    TSM = 'TSM',
    MA = 'MA',
    GS = 'GS',
    UBER = 'UBER',
    CRWD = 'CRWD',
    BA = 'BA',
    DJT = 'DJT',
    HIMS = 'HIMS',
    IBM = 'IBM',
    JNJ = 'JNJ',
    LMT = 'LMT',
    LULU = 'LULU',
    MGM = 'MGM',
    PFE = 'PFE',
    QUBT = 'QUBT',
    RBLX = 'RBLX',
    RDDT = 'RDDT',
    RIVN = 'RIVN',
    SHOP = 'SHOP',
    SNAP = 'SNAP',
    UPS = 'UPS',
    BP = 'BP',
    LIT = 'LIT',
    SILV = 'SILV',
    TAO = 'TAO',
    DOGE = 'DOGE',
    MORPHO = 'MORPHO',
    SV151 = 'SV151',
    PEAQ = 'PEAQ',
    PSG = 'PSG',
    PONS = 'PONS',
    ARB = 'ARB',
    SLX = 'SLX',
    CHIP = 'CHIP',
    BILL = 'BILL',
    CASHCAT = 'CASHCAT',
    PUMP = 'PUMP',
    BABA = 'BABA',
    BULL = 'BULL',
    COST = 'COST',
    DELL = 'DELL'
}
const QUOTE_MINTS: Record<Quote, { mint: PublicKey; token_program: PublicKey; decimals: number }> = {
    [Quote['SOL']]: {
        mint: new PublicKey('So11111111111111111111111111111111111111112'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 9
    },
    [Quote['USDC']]: {
        mint: new PublicKey('EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 6
    },
    [Quote['BTC']]: {
        mint: new PublicKey('3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['ETH']]: {
        mint: new PublicKey('7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['MU']]: {
        mint: new PublicKey('MUxEsUKSMACyw5fZf68wxf5FLnZVhtU9CwH8uNNGay1'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['SPY']]: {
        mint: new PublicKey('XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['CRCL']]: {
        mint: new PublicKey('XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['SKHY']]: {
        mint: new PublicKey('SKHYhSjuRWHgikq8eRKbtBbpABgJSkd7ytQV14i9EQ3'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['TSLA']]: {
        mint: new PublicKey('XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['QQQ']]: {
        mint: new PublicKey('Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['NVDA']]: {
        mint: new PublicKey('Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['SPCX']]: {
        mint: new PublicKey('SPCXxcqXj6e5dJDVNovHN8744zkbhM2bYudU45BimGb'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['MSTR']]: {
        mint: new PublicKey('XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['COIN']]: {
        mint: new PublicKey('Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['GLD']]: {
        mint: new PublicKey('Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['HOOD']]: {
        mint: new PublicKey('XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['VIDA']]: {
        mint: new PublicKey('XsfCC9VL4DamVGNgdJpfLXB3sBVa158Gbx8sh7NzmTk'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['AAPL']]: {
        mint: new PublicKey('XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['MCD']]: {
        mint: new PublicKey('XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['NKE']]: {
        mint: new PublicKey('NKEda5nHhNGgjrE9nDdMvaEmkmJ96qqxzBVZEcKmjSg'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['DRAM']]: {
        mint: new PublicKey('DRAMjSWR7HRfJKjRkvQWYL2bcaejaVhuxEcjf4pAY4Cw'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['PLTR']]: {
        mint: new PublicKey('XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['MSFT']]: {
        mint: new PublicKey('XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['BOT']]: {
        mint: new PublicKey('BoTx8y9ynfdxf5ZjWtCoBVkff52qKA82ysaLU8ZM6d8T'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['GOOGL']]: {
        mint: new PublicKey('XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['TTWO']]: {
        mint: new PublicKey('TTWofwAge91oFhZs7kpQdyrVRkmevgM88xijGvQFbKo'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['GPRO']]: {
        mint: new PublicKey('GPRR2u6NS5yBQHWGauoJ9HXgjrTH8dDsrBfTV5zAYvDH'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['META']]: {
        mint: new PublicKey('Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['AMZN']]: {
        mint: new PublicKey('Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['KO']]: {
        mint: new PublicKey('XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['GME']]: {
        mint: new PublicKey('Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['BRK.B']]: {
        mint: new PublicKey('Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['SNDK']]: {
        mint: new PublicKey('SNDKbwMUQvZhnLnxLduradgLHG5KrPuKwpnrkkGRhfH'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['AMC']]: {
        mint: new PublicKey('AMC1qwR9KhiyrQBRPrxnfo4JfMeMZqEBvt5tgTytNNoc'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['MRNA']]: {
        mint: new PublicKey('MRNAzXzhNcaEXJPibHEn8cd4vyekCDiivTyEwswLUCT'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['AVGO']]: {
        mint: new PublicKey('XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['LLY']]: {
        mint: new PublicKey('LLYuwZ33keFihgwoxXsBawy31AiRFLFSva32TYq5TvD'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['INTC']]: {
        mint: new PublicKey('iNTCy1qTsUEZQe3DSocLz1ZXXai34Gdw8THQh5rxFaF'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['HYPE']]: {
        mint: new PublicKey('98sMhvDwXj1RQi5c5Mndm3vPe9cBqPrbLaufMXFNMh5g'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 9
    },
    [Quote['ZEC']]: {
        mint: new PublicKey('A7bdiYdS5GjqGFtxf17ppRHtDKPkkRqbKtR27dxvQXaS'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['NEAR']]: {
        mint: new PublicKey('3ZLekZYq2qkZiSpnSvabjit34tUkjSwD1JFuW9as9wBG'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 9
    },
    [Quote['XRP']]: {
        mint: new PublicKey('6UpQcMAb5xMzxc7ZfPaVMgx3KqsvKZdT5U718BzD5We2'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 6
    },
    [Quote['XMR']]: {
        mint: new PublicKey('WXMRyRZhsa19ety5erZhHg4N3xj3EVN92u94422teJp'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 12
    },
    [Quote['NBIS']]: {
        mint: new PublicKey('NBiSF3UaVUFtRzHwAfxyHsBCAZWGEKnMpewAE4oh7BG'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['MRVL']]: {
        mint: new PublicKey('MRVLSjkR2ceUBukujaD3xCyHP1H3B2SzpsNTZF546jo'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['ORCL']]: {
        mint: new PublicKey('XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['XOM']]: {
        mint: new PublicKey('XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['UNH']]: {
        mint: new PublicKey('XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['NFLX']]: {
        mint: new PublicKey('XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['NVO']]: {
        mint: new PublicKey('XsfAzPzYrYjd4Dpa9BU3cusBsvWfVB9gBcyGC87S57n'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['AMD']]: {
        mint: new PublicKey('XsXcJ6GZ9kVnjqGsjBnktRcuwMBmvKWh8S93RefZ1rF'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['V']]: {
        mint: new PublicKey('XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['JPM']]: {
        mint: new PublicKey('XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['WMT']]: {
        mint: new PublicKey('Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['TSM']]: {
        mint: new PublicKey('XsafvsGtzFqqHgTnA3aPC83EAMkacU5mcGtcSayhpVV'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['MA']]: {
        mint: new PublicKey('XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['GS']]: {
        mint: new PublicKey('XsgaUyp4jd1fNBCxgtTKkW64xnnhQcvgaxzsbAq5ZD1'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['UBER']]: {
        mint: new PublicKey('XsAsZLF4MmsvS1sDxRMrUz7REjHfwbC9UAMXSRBqgEB'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['CRWD']]: {
        mint: new PublicKey('Xs7xXqkcK7K8urEqGg52SECi79dRp2cEKKuYjUePYDw'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 8
    },
    [Quote['BA']]: {
        mint: new PublicKey('BArimz1PcKZr8PcPh3tcZ2dg4S7FJLk3cw6R5F8GsHKg'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['DJT']]: {
        mint: new PublicKey('DJTu7vi8norVzdVAffgvb39VP7wjKeTsgaMBJrzfxvoF'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['HIMS']]: {
        mint: new PublicKey('HiMSSzzwkZkrXJ4PGVJRdtfLaANeAztjjcgk5Dxe7Lwx'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['IBM']]: {
        mint: new PublicKey('BMKdM4yUxX12moFqVk195k7coMbaybd4RUKCUdm7D1Sk'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['JNJ']]: {
        mint: new PublicKey('JNJg1znKdF712Phe7L7z52AATAvEjEytBdN2w8Lnh1Y'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['LMT']]: {
        mint: new PublicKey('LMT3i1BHgixFqPUgcyteJhnEz2dpy9i3cYy4pi9BoeV'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['LULU']]: {
        mint: new PublicKey('LULUmT9VMttkfAJE236LXJcYJ2tTP7nunrSWR5G1BdS'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['MGM']]: {
        mint: new PublicKey('MGMuubtUEirmkhfEQdmGUh4pr7HuUdMWcZXFtpPbVJD'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['PFE']]: {
        mint: new PublicKey('PFER6ENqP8r8NF3CqVt4mFowxsin3V5MLidBNQFCC3x'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['QUBT']]: {
        mint: new PublicKey('QUBTAD8C9bMU9LvmMNgKPhrmBGbHvxpu6vfWQtThxxw'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['RBLX']]: {
        mint: new PublicKey('RBLXDGRD64AtRamHMFVcjqne3Ar7NLWtFtYNtsrf1cE'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['RDDT']]: {
        mint: new PublicKey('RDDTGbhHwVXfyCvQMXzzowKjf5qrYBZAnehoXW83ooh'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['RIVN']]: {
        mint: new PublicKey('RcZmt84VMJv9bDhKqmw1uWDahYrUT468VwAChTnfD8p'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['SHOP']]: {
        mint: new PublicKey('SH55hfaipFAbwT42nQYhRoM5o5t61QpkmJ6p62vXB3m'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['SNAP']]: {
        mint: new PublicKey('SNAPcESrvnH8yUdgeMF6xm1hym9b6hW6s8YeqeHdZFz'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['UPS']]: {
        mint: new PublicKey('UPSqUeMHcWbkdg784XuBUEF9DtySSnW9ur5LAVdcuB9'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['BP']]: {
        mint: new PublicKey('BPxxfRCXkUVhig4HS1Lh7kZqV6SPJhzfEk4x6fVBjPCy'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 9
    },
    [Quote['LIT']]: {
        mint: new PublicKey('EicWvteVi2fWepEzS3FYWsnuPoP6caZfjnKqNvydLjCH'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['SILV']]: {
        mint: new PublicKey('SiLVFMgD3eD2rgK628NbTBq9MnuJF5FW2CRaVyTB35L'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['TAO']]: {
        mint: new PublicKey('taoC6xyv2v8tDLcev4uaGUgV4vdQsWJrGft2kcBRrBY'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 9
    },
    [Quote['DOGE']]: {
        mint: new PublicKey('DoGEV7LASBkQbibMc5k5vKnTZoMg423GpJ5QtJEGfm7R'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['MORPHO']]: {
        mint: new PublicKey('Morpho2VPeTr2E1Jx6monxCzF7mqwUnjz74RdwLXYyP'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['SV151']]: {
        mint: new PublicKey('SV151D5pjygAKA8aJJcKzm4wFnRX5G92Fye94jQJk7g'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 6
    },
    [Quote['PEAQ']]: {
        mint: new PublicKey('PEAQjk7SRS6rXHVFFmpRr7zrC4g5ZuEebpwTxvaLr3b'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 9
    },
    [Quote['PSG']]: {
        mint: new PublicKey('5eyib4qghYGHNh7VvxSFGYLFJSanjq9hug9fR52kksnm'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 9
    },
    [Quote['PONS']]: {
        mint: new PublicKey('poNSfquKq512ApeYjVghwViSun4x1MhCqHVH2Paq4jN'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['ARB']]: {
        mint: new PublicKey('ARBzQTYDCW2KnVEjs1Mc81LekB1ibVFZKbSVmorkoT9d'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['SLX']]: {
        mint: new PublicKey('SLXdx4BUt2v9uJQNzWqSfzTJ9UKLUDsvxHFMEEdrfgq'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 6
    },
    [Quote['CHIP']]: {
        mint: new PublicKey('chipCAT7vi5CZtbZsn9z7iMPXvFwyAnKz3QFu8XVuHm'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 9
    },
    [Quote['BILL']]: {
        mint: new PublicKey('Bi11Je4MH3PpyCNiuTAepRbsA5U6DK3DJy79ZFthddX'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['CASHCAT']]: {
        mint: new PublicKey('CashcatZMRn4Jv8sPQZUSsbTLi2PcPe1ssqbHcnaJqSS'),
        token_program: TOKEN_PROGRAM_ID,
        decimals: 8
    },
    [Quote['PUMP']]: {
        mint: new PublicKey('pumpCmXqMfrsAkQ5r49WcJnRayYRqmXz6ae8H7H9Dfn'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['BABA']]: {
        mint: new PublicKey('BABANGA4JE7Kkam4nTrALAwAVgsNJUuFJnnkF7S16BZp'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['BULL']]: {
        mint: new PublicKey('BULL151gUXcFV5wXEUqu9Am2L7Qt4bTJRLRuAUjkcspC'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['COST']]: {
        mint: new PublicKey('CZEB3WNZuF2Yz1z2H81RcCk8T7fsw82KB33zqamASVsg'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    },
    [Quote['DELL']]: {
        mint: new PublicKey('DELL2aRKQz7DMq5DrKLtkn47ZCnbxXPZXrSGbkmd13wy'),
        token_program: TOKEN_2022_PROGRAM_ID,
        decimals: 6
    }
};

const quotes_by_mint = new Map<string, (typeof QUOTE_MINTS)[Quote]>(
    Object.values(QUOTE_MINTS).map((quote) => [quote.mint.toBase58(), quote])
);
const quotes_by_ticker = new Map(Object.entries(QUOTE_MINTS).map(([ticker, quote]) => [ticker.toLowerCase(), quote]));
const quote_names_by_mint = new Map<string, string>(
    Object.entries(QUOTE_MINTS).map(([ticker, quote]) => [quote.mint.toBase58(), ticker])
);

export function get_quote_by_mint(mint: PublicKey | string) {
    return quotes_by_mint.get(typeof mint === 'string' ? mint : mint.toBase58());
}

export function get_quote_name_by_mint(mint: PublicKey | string) {
    return quote_names_by_mint.get(typeof mint === 'string' ? mint : mint.toBase58());
}

export function get_quote_by_ticker(ticker: string) {
    return quotes_by_ticker.get(ticker.toLowerCase());
}

export function is_quote(value: string): value is Quote {
    return Object.values(Quote)
        .map((s) => s.toLowerCase())
        .includes(value.toLowerCase() as Quote);
}
